global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-demo"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.100.63:8080"]
        labels:
          application: "api-demo"